name: call-reusable-workflow
on:push:
  branches:
    - main

jobs:
  call-reusable-workflow:
    uses: Saptarshi666/github-actions-basic-to-advance/.github/workflows/resusableSaptarshi.yml@main
  call-reusable-workflow2:
    uses: bgerelmaa/github-actions-basic-to-advance/.github/workflows/reusable-workflow.yml@main
